# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

      # Service container image available at `host: localhost`
    - image: circleci/mysql:5.7.26
      environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_USER: root
        MYSQL_DATABASE: auditdb
        MYSQL_PASSWORD: 'P@ssw0rd#'

    working_directory: ~/audit4jusage

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - run:
        name: Wait for Database Connection
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://localhost:3306 -timeout 120s

    # Download and cache dependencies
    - restore_cache:
        keys:
        - audit4jusage-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - audit4jusage-

        # prepare the database
    #- run: mysqladmin create auditdb --host="127.0.0.1" --user="root" --password="P@ssw0rd#"
    - run:
        name: Install MySQL CLI
        command: |
          sudo apt-get install mysql-client
          mysql -h 127.0.0.1 -u 'root' -p '' create database auditdb

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: audit4jusage-{{ checksum "pom.xml" }}

    - run: mvn spring-boot:run


    - store_test_results:
        path: target/surefire-reports