# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

      # Service container image available at `host: localhost`
    - image: circleci/mysql:5.7.26

    working_directory: ~/audit4jusage

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_USER: 'root'
      MYSQL_DB: circle-test

    steps:
    - checkout

    - run:
        name: Wait for Database Connection
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
        environment:
          DATABASE_URL: "jdbc:mysql://localhost:3306/circle-test?useSSL=FALSE"



    # Download and cache dependencies
    - restore_cache:
        keys:
        - audit4jusage-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - audit4jusage-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: audit4jusage-{{ checksum "pom.xml" }}

    - run: mvn spring-boot:run


    - store_test_results:
        path: target/surefire-reports